# Generated by Django 5.2.7 on 2025-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
