const pickupLines = [
  "Are you a magician? Every time I look at you, everyone else disappears.",
  "Do you have a map? I just keep getting lost in your eyes.",
  "Excuse me, but I think you dropped something: my jaw.",
  "You're like a fine wine, you get better with age.",
  "Do you believe in love at first sight, or should I walk by again?",
  "I must be a snowflake, because I've fallen for you.",
  "Excuse me, do you have a name? Or can I just call you mine?",
  "Is your name Wi-Fi? Because I'm feeling a connection.",
  "You're like a puzzle piece that fits perfectly into my life.",
  "Do you like Star Wars? Because Yoda one for me: 'You are my everything.'",
  "Are you an alien? Because you're out of this world.",
  "Do you have a library card? Because I want to check you out.",
  "You're like a camera, because every time I look at you, I smile.",
  "Do you like pineapple pizza? Because you're a fruit-tastic catch.",
  "I'm not a photographer, but I can picture us together.",
  "Do you like coffee? Because I like you a latte.",
  "You're a real-life player two.",
  "You light up the room like a supernova.",
  "Your smile is the brightest thing I've ever seen.",
  "I'd love to be the cream to your coffee, the sugar to your tea.",
  "Are you a sunset? Because you're making my heart skip a beat.",
  "Do you have a map to your heart? I'd love to explore it.",
  "You're like a dream, and I'm not sure if I'll ever wake up.",
  "In a world full of stars, you're my moon – my guiding light.",
  "Do you believe in fate? Because I feel like I've been searching for you my whole life.",
  "Are you an architect? Because you're building a structure in my heart.",
  "Do you like gardening? Because you're growing on me.",
  "You're like a recipe – a perfect blend of sweet and savory.",
  "Are you a timekeeper? Because you're running ahead of my heart.",
  "Do you like puzzles? Because you're piecing together my thoughts.",
  "If I could rearrange the alphabet, I'd put 'U' and 'I' together.",
  "You're the missing piece to my favorite song – the one that's been playing in my head.",
  "Do you have a favorite scent? Because you smell like home.",
  "Are you a library book? Because I'm checking you out.",
  "You're the reason I wake up with a smile – or maybe it's just the coffee.",
  "Are you a coffin? Because you're burying me in your eyes.",
  "Do you have a death wish? Because I'm dying to meet you.",
  "You're so dark, you make the night look bright.",
  "Are you a ghost? Because you're haunting my thoughts.",
  "Do you believe in the afterlife? Because I'm dying to be with you.",
  "You're like a black hole – drawing me in with an irresistible force.",
  "Are you a vampire? Because you're sucking me dry.",
  "Do you have a taste for blood? Because I'm bleeding for you.",
  "You're like a curse – one I'm willing to live with.",
  "Are you a nightmare? Because you're keeping me up at night.",
  "You're my poison – the one I'm addicted to.",
  "Do you like pain? Because you're hurting me in the best way.",
  "Are you a masochist? Because you're making me love the pain.",
  "You're like a razor – cutting through my defenses.",
  "Do you believe in toxic love? Because I'm intoxicated by you.",
  "Are you a zombie apocalypse? Because you're infecting me with your love.",
  "Do you like cemeteries? Because I'd love to be buried with you.",
  "You're like a plague – one I'm willing to catch.",
  "Are you a funeral? Because you're mourning the loss of my heart.",
  "Do you believe in dying for love? Because I'd die for you.",
  "Are you made of copper and tellurium? Because you’re Cu-Te.",
  "Are you French? Because Eiffel for you.",
  "Do you have a name, or can I call you mine?",
  "Your body is 70% water and I’m thirsty.",
  "If I were a cat, I’d spend all 9 lives with you… preferably in your bed.",
  "Do you have a map? Because I just got lost in your eyes… and maybe your curves too.",
  "Is your name Wi-Fi? Because I’m feeling a strong connection.",
  "Are you a magician? Because whenever you're around, everything else disappears—including my clothes, hopefully.",
  "If I followed you home, would you keep me?",
  "You must be a campfire, because you’re hot and I want s’more.",
  "Do you believe in karma? Because I think you owe me a night of passion.",
  "Is your name Google? Because you’ve got everything I’ve been searching for… and then some.",
  "If being sexy was a crime, you’d be serving a life sentence — and I’d be your cellmate.",
  "Do you have a mirror in your pants? Because I can see myself in them.",
  "Are you a drill sergeant? Because every time I see you, my knees go weak.",
  "Are you sitting on the F5 key? Because that booty is refreshing.",
  "I’m not a weatherman, but you can expect a few inches tonight.",
  "Do you work at Subway? Because you just gave me a footlong.",
  "Are you a campfire? Because you’re hot and I want to roast my marshmallow on you.",
  "Forget hydrogen — you should be the number one element in my universe… right after ‘U and I in bed’.",
  "I must be a snowflake, because I’ve fallen for you.",
  "Every love song suddenly makes sense when I think of you.",
  "I didn’t believe in soulmates until I looked into your eyes.",
  "I wasn’t planning on falling in love, but then you smiled at me.",
  "You’re the reason I check my phone with a smile every few minutes.",
  "Do you have a compass? Because I keep getting lost in your eyes.",
  "Your hand looks heavy — can I hold it for you?",
  "You’re like a sunrise — beautiful, warm, and the start of something amazing.",
  "If kisses were stars, I’d give you the sky.",
  "I must be dreaming, because every time I look at you, the world fades away.",
  "I’d walk through fire just to feel your cold touch.",
  "Your love feels like a beautiful curse I never want to break.",
  "Even in my nightmares, I crave the warmth of your soul.",
  "Loving you is like drowning — terrifying, overwhelming, and utterly irresistible.",
  "I don’t fear the darkness… I only fear a life without you in it.",
  "You’re the poison I’d gladly drink if it meant dying in your arms.",
  "If my heart were a grave, your name would be carved deep into the stone.",
  "You haunt my thoughts like a ghost that refuses to be forgotten.",
  "If love is madness, then let me lose my mind in you.",
  "Some call it obsession — I call it knowing exactly what my soul wants."
];
export default pickupLines;